export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripePublishableKey: process.env.VITE_STRIPE_PUBLISHABLE_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  stripePriceBeginner: process.env.STRIPE_PRICE_BEGINNER ?? "price_1STuz1H2oBnqcEomh4WSJRIl",
  stripePriceIntermediary: process.env.STRIPE_PRICE_INTERMEDIARY ?? "price_1STuzuH2oBnqcEomhyAwrSzO",
  stripePriceProficient: process.env.STRIPE_PRICE_PROFICIENT ?? "price_1STv0RH2oBnqcEomz8GFluWi",
  stripePriceBundle: process.env.STRIPE_PRICE_BUNDLE ?? "price_1STv14H2oBnqcEomPdWXNq6H",
};
